services:
  php-oracle-app:
    build:
      context: ../..
      dockerfile: docker/apps/php/Dockerfile
    container_name: php-oracle-app
    env_file:
      - .env
    network_mode: host
    volumes:
      - ./php-app:/var/www/html:ro
    restart: unless-stopped

