version: '3.8'

services:
  nextjs:
    build:
      context: ./my-app
      dockerfile: ../Dockerfile
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_PUBLIC_API_URL=http://nestjs:3001
    networks:
      - apps-net

networks:
  apps-net:
    driver: bridge
    external: true
    name: apps-net