services:
  api-portal:
    build:
      context: ../..
      dockerfile: docker/apps/nestjs/Dockerfile
    container_name: nestjs-api-portal
    restart: unless-stopped
    network_mode: host
    environment:
      - PORT=3003
      - NODE_ENV=production
    env_file:
      - ./api-portal/.env

