services:
  api-portal:
    build:
      context: ../..
      dockerfile: docker/apps/nestjs/Dockerfile
      args:
        - APP_NAME=api-portal
    container_name: nestjs-api-portal
    restart: unless-stopped
    network_mode: host
    environment:
      - PORT=3003
      - NODE_ENV=production
    env_file:
      - ./api-portal/.env

  api-autenticacion:
    build:
      context: ../..
      dockerfile: docker/apps/nestjs/Dockerfile
      args:
        - APP_NAME=api-autenticacion
    container_name: nestjs-api-autenticacion
    restart: unless-stopped
    network_mode: host
    environment:
      - PORT=3004
      - NODE_ENV=production
    env_file:
      - ./api-autenticacion/.env

