version: '3.8'

services:
  nestjs:
    build:
      context: ./nest-app
      dockerfile: ../Dockerfile
    container_name: nestjs-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
    networks:
      - apps-net

networks:
  apps-net:
    driver: bridge
    external: true
    name: apps-net